services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
  listener:
    build:
      context: .
      dockerfile: listener/Dockerfile
    restart: always
    env_file:
      - .env
    depends_on:
      - redis
  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    restart: always
    ports:
      - "5001:5001"
    env_file:
      - .env
    depends_on:
      - redis

