services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
  listener:
    build:
      context: .
      dockerfile: listener/Dockerfile
    restart: always
    env_file:
      - .env
    depends_on:
      - redis
  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    restart: always
    ports:
      - "5001:5001"
    env_file:
      - .env
    depends_on:
      - redis
  # metricclient:
  #   build:
  #     context: .
  #     dockerfile: metricclient/Dockerfile
  #   restart: always
  #   env_file:
  #     - .env
  #   depends_on:
  #     - redis
  mock_trader_v1:
    network_mode: service:gluetun
    build:
      context: .
      dockerfile: trader/Dockerfile
    restart: always
    env_file:
      - .env
    depends_on:
      - redis
      - listener
  gluetun:
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - VPN_SERVICE_PROVIDER=protonvpn
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - SERVER_COUNTRIES=Ireland
